/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.template;

import java.net.URL;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.scene.control.Label;
import java.util.List;
import java.util.Optional;
import javafx.scene.control.ChoiceDialog;


public class App extends Application
{
    private static final int SIZE = 8;
    // this is the size of each square in the chess or checkers board
    // this must be kept in sync with the size of the images, and the
    // size of the squares in the css file
    private static final int SQUARE_SIZE = 70;
    private VBox root;
    // using StackPane so that they can hold a rectangle and an image
    // we use the rectangle to color the squares
    // and the image to place the pieces
    private StackPane[][] grid = new StackPane[SIZE][SIZE];
    private Board model = new Board();
    private int selectedRow = -1;
    private int selectedCol = -1;
    private Player currentPlayer = Player.WHITE; // WHITE starts
    private Label turnLabel = new Label("Turn: WHITE");
    private boolean gameOver = false;






    @Override
    public void start(Stage primaryStage) throws Exception
    {
        root = new VBox();

        // Style the turn label and add it first
        turnLabel.setStyle("-fx-font-size: 18px; -fx-font-weight: bold; -fx-padding: 8;");
        root.getChildren().add(turnLabel);

        // Then add the menu bar
        root.getChildren().add(createMenuBar());


        GridPane gridPane = new GridPane();
        // preferred size of the gridpane
        gridPane.setPrefSize(SQUARE_SIZE * 8, SQUARE_SIZE * 8);
        
        root.getChildren().add(gridPane);
        

        // loosely based on https://stackoverflow.com/questions/69339314/how-can-i-draw-over-a-gridpane-of-rectangles-with-an-image-javafx
        for (int row = 0; row < SIZE; row++)
        {
            for (int col = 0; col < SIZE; col++)
            {
                Rectangle rect = new Rectangle(SQUARE_SIZE, SQUARE_SIZE);

                if ((row + col) % 2 == 0) { 
                    rect.getStyleClass().add("white-square");
                }
                else {
                    rect.getStyleClass().add("black-square");
                }
                
                StackPane cell = new StackPane(rect);
                
                grid[row][col] = cell;

                // name each cell with its row and column
                // unsure we'll need this
                cell.setId(row + "-" + col);

                // we need to create these extra local final variables
                // I think this has to do with thread safety?
                final int r = row;
                final int c = col;
                // make each cell clickable
                cell.setOnMouseClicked(event -> handleMouseClick(event, r, c));

                // finally, put the stackpane into the gridpane
                gridPane.add(cell, col, row);
            }
        }

        // don't give a width or height to the scene
        // it will figure it out because there's a menu bar
        // plus each square is a fixed size
        Scene scene = new Scene(root);

        // add style information
        URL styleURL = getClass().getResource("/style.css");
        String stylesheet = styleURL.toExternalForm();
        scene.getStylesheets().add(stylesheet);

        // set title and scene and show to the user
        primaryStage.setTitle("GAME TEMPLATE");
        primaryStage.setScene(scene);
        primaryStage.show();

        drawInitialBoard();

        // handler for when we click the close button
        primaryStage.setOnCloseRequest(event -> {
            System.out.println("oncloserequest");
        });

    }

    private void clearBoard()
    {
        // removes all of the images (pieces) from the board
        for (int row = 0; row < SIZE; row++)
        {
            for (int col = 0; col < SIZE; col++)
            {
                grid[row][col].getChildren().removeIf(child -> child instanceof ImageView);
            }
        }
    }

    private void drawBoard1()
    {
        clearBoard();
        placePiece(Player.WHITE, ChessPiece.PAWN, 1, 1);
        placePiece(Player.WHITE, ChessPiece.PAWN, 2, 3);
        placePiece(Player.BLACK, ChessPiece.ROOK, 3, 0);
        placePiece(Player.BLACK, ChessPiece.QUEEN, 4, 0);
    }

    private void drawBoard2()
    {
        clearBoard();
        placePiece(Player.WHITE, ChessPiece.PAWN, 1, 4);
        placePiece(Player.WHITE, ChessPiece.PAWN, 2, 4);
        placePiece(Player.BLACK, ChessPiece.ROOK, 3, 4);
        placePiece(Player.BLACK, ChessPiece.QUEEN, 4,4);
    }

    private void setKeyboardHandler()
    {
        // add this to the root which is a VBox
        root.setOnKeyPressed(event -> {
            System.out.println("Key pressed: " + event.getCode());
            switch (event.getCode())
            {
                // check for the key input
                case ESCAPE:
                    // remove focus from the textfields by giving it to the root VBox
                    root.requestFocus();
                    System.out.println("You pressed ESC key");
                    break;
                case ENTER:
                    System.out.println("You pressed ENTER key");
                    break;
                default:
                    System.out.println("you typed key: " + event.getCode());
                    break;
                
            }
        });
    }

    private void showAvailableMoves(int fromRow, int fromCol) {
        ChessPiece piece = model.getPiece(fromRow, fromCol);
        Player owner = model.getOwner(fromRow, fromCol);

        boolean inCheck = model.isInCheck(owner);

        for (int toRow = 0; toRow < SIZE; toRow++) {
            for (int toCol = 0; toCol < SIZE; toCol++) {
                boolean isValid = switch (piece) {
                    case PAWN -> model.isValidPawnMove(fromRow, fromCol, toRow, toCol);
                    case ROOK -> model.isValidRookMove(fromRow, fromCol, toRow, toCol);
                    case BISHOP -> model.isValidBishopMove(fromRow, fromCol, toRow, toCol);
                    case KNIGHT -> model.isValidKnightMove(fromRow, fromCol, toRow, toCol);
                    case KING -> model.isValidKingMove(fromRow, fromCol, toRow, toCol);
                    case QUEEN -> model.isValidQueenMove(fromRow, fromCol, toRow, toCol);
                };

                if (!isValid) continue;

                if (inCheck) {
                    // Simulate the move
                    ChessPiece tempPiece = model.getPiece(toRow, toCol);
                    Player tempOwner = model.getOwner(toRow, toCol);
                    model.setPiece(toRow, toCol, piece, owner);
                    model.clearSquare(fromRow, fromCol);

                    boolean stillInCheck = model.isInCheck(owner);

                    // Undo
                    model.setPiece(fromRow, fromCol, piece, owner);
                    model.setPiece(toRow, toCol, tempPiece, tempOwner);

                    if (!stillInCheck) {
                        highlightSquare(toRow, toCol, "move-option");
                    }
                } else {
                    highlightSquare(toRow, toCol, "move-option");
                }
            }
        }

        highlightSquare(fromRow, fromCol, "selected");
    }

    private void disableAllMoves() {
        gameOver = true;
        turnLabel.setText("Game Over. " + (currentPlayer == Player.WHITE ? "Black" : "White") + " wins!");
    }



    private void handleMouseClick(MouseEvent event, int row, int col) {
        if (gameOver) {
            System.out.println("Game is over. No more moves allowed.");
            return;
        }

        clearHighlights(); // Always start by clearing previous highlights

        if (selectedRow == -1 && selectedCol == -1) {
            if (model.isOccupied(row, col) && model.getOwner(row, col) == currentPlayer) {
                selectedRow = row;
                selectedCol = col;
                showAvailableMoves(row, col);  // 🔥 Show moves
            } else {
                System.out.println("Not your turn or empty square.");
            }
        } else {
            // Second click - attempt to move
            ChessPiece piece = model.getPiece(selectedRow, selectedCol);
            Player owner = model.getOwner(selectedRow, selectedCol);

            boolean isValid = false;

            if (owner != currentPlayer) {
                System.out.println("It's not your turn.");
            } else {
                switch (piece) {
                    case PAWN:
                        isValid = model.isValidPawnMove(selectedRow, selectedCol, row, col);
                        break;
                    case ROOK:
                        isValid = model.isValidRookMove(selectedRow, selectedCol, row, col);
                        break;
                    case BISHOP:
                        isValid = model.isValidBishopMove(selectedRow, selectedCol, row, col);
                        break;
                    case KNIGHT:
                        isValid = model.isValidKnightMove(selectedRow, selectedCol, row, col);
                        break;
                    case KING:
                        isValid = model.isValidKingMove(selectedRow, selectedCol, row, col);
                        break;
                    case QUEEN:
                        isValid = model.isValidQueenMove(selectedRow, selectedCol, row, col);
                        break;
                }
            }

            if (isValid) {
                // Simulate the move
                ChessPiece capturedPiece = model.getPiece(row, col);
                Player capturedOwner = model.getOwner(row, col);

                model.setPiece(row, col, piece, owner);
                model.clearSquare(selectedRow, selectedCol);

                boolean kingStillSafe = !model.isInCheck(owner);

                if (kingStillSafe) {
                    // Promote pawn if needed
                if (piece == ChessPiece.PAWN && (row == 0 || row == 7)) {
                    ChessPiece promotedPiece = showPromotionDialog(owner);
                    model.setPiece(row, col, promotedPiece, owner);
                } else {
                    model.setPiece(row, col, piece, owner);
                }


                    drawInitialBoard();
                    currentPlayer = (currentPlayer == Player.WHITE) ? Player.BLACK : Player.WHITE;
                    turnLabel.setText("Turn: " + currentPlayer);

                    if (!model.isKingAlive(currentPlayer)) {
                        turnLabel.setText("Checkmate! " + (currentPlayer == Player.WHITE ? "Black" : "White") + " wins!");
                        gameOver = true;
                        return;
                    }

                    if (model.isCheckmate(currentPlayer)) {
                        turnLabel.setText("Checkmate! " + (currentPlayer == Player.WHITE ? "Black" : "White") + " wins!");
                        disableAllMoves();
                        return;
                    }

                } else {
                    // Undo the move — it's illegal
                    model.setPiece(selectedRow, selectedCol, piece, owner);
                    model.setPiece(row, col, capturedPiece, capturedOwner);
                    System.out.println("Move leaves king in check. Not allowed.");
                }
            }

            if (!model.isKingAlive(currentPlayer)) {
                turnLabel.setText("Checkmate! " + (currentPlayer == Player.WHITE ? "Black" : "White") + " wins!");
                gameOver = true;
                return;
            }




            selectedRow = -1;
            selectedCol = -1;
            clearHighlights(); // 🔥 clear all after second click

        }

        if (model.isCheckmate(currentPlayer)) {
            turnLabel.setText("Checkmate! " + (currentPlayer == Player.WHITE ? "Black" : "White") + " wins!");
            disableAllMoves(); // You'll need to implement this
            return;
        }

    }
    private void restartGame() {
        model = new Board();
        currentPlayer = Player.WHITE;
        turnLabel.setText("Turn: WHITE");
        selectedRow = -1;
        selectedCol = -1;
        clearHighlights();
        drawInitialBoard();
        gameOver = false; // Allow moves again
    }
    private ChessPiece showPromotionDialog(Player player) {
        List<ChessPiece> choices = List.of(ChessPiece.QUEEN, ChessPiece.ROOK, ChessPiece.BISHOP, ChessPiece.KNIGHT);
        ChoiceDialog<ChessPiece> dialog = new ChoiceDialog<>(ChessPiece.QUEEN, choices);
        dialog.setTitle("Pawn Promotion");
        dialog.setHeaderText("Choose piece for promotion");
        dialog.setContentText("Promote pawn to:");

        Optional<ChessPiece> result = dialog.showAndWait();
        return result.orElse(ChessPiece.QUEEN); // Default to Queen if closed
    }




    private void placePiece(Player player, ChessPiece piece, int row, int col)
    {
        String imageName = "";
        if (player == Player.WHITE)
        {
            imageName = "w" + piece.toString().toLowerCase() + ".png";
        }
        else
        {
            imageName = "b" + piece.toString().toLowerCase() + ".png";
        }
        ImageView image = loadImage(imageName);
        // add the image to the cell
        // each cell is stack pane so that we can "stack" the piece
        // on top of the rectangle for the square
        grid[row][col].getChildren().add(image);
        // not sure if any of this was necessary; commenting it out didn't seem to matter
        image.setFitWidth(SQUARE_SIZE);
        image.setFitHeight(SQUARE_SIZE);
        //image.fitWidthProperty().bind(grid[row][col].widthProperty().subtract(2));
        //image.fitHeightProperty().bind(grid[row][col].heightProperty().subtract(2));
    }

    private ImageView loadImage(String name)
    {
        return new ImageView(getClass().getResource("/assets/" + name).toExternalForm());
    }
    private MenuBar createMenuBar() {
        MenuBar menuBar = new MenuBar();
        menuBar.getStyleClass().add("menubar");

        Menu fileMenu = new Menu("File");

        addMenuItem(fileMenu, "Load from file", () -> {
            System.out.println("Load from file");
        });

        addMenuItem(fileMenu, "board1", this::drawBoard1);
        addMenuItem(fileMenu, "board2", this::drawBoard2);
        addMenuItem(fileMenu, "Restart Game", this::restartGame); // <== Added

        menuBar.getMenus().add(fileMenu);
        return menuBar;
    }




    private void addMenuItem(Menu menu, String name, Runnable action)
    {
        MenuItem menuItem = new MenuItem(name);
        menuItem.setOnAction(event -> action.run());
        menu.getItems().add(menuItem);
    }
    private void drawInitialBoard() {
        clearBoard();
        for (int row = 0; row < SIZE; row++) {
            for (int col = 0; col < SIZE; col++) {
                if (model.isOccupied(row, col)) {
                    placePiece(model.getOwner(row, col), model.getPiece(row, col), row, col);
                }
            }
        }
    }
    private void clearHighlights() {
        for (int row = 0; row < SIZE; row++) {
            for (int col = 0; col < SIZE; col++) {
                Rectangle rect = (Rectangle) grid[row][col].getChildren().get(0);

                // Restore the default color
                if ((row + col) % 2 == 0) {
                    rect.setFill(Color.ANTIQUEWHITE);  // for white-square
                } else {
                    rect.setFill(Color.CHOCOLATE);     // for black-square
                }
            }
        }
    }



    private void highlightSquare(int row, int col, String type) {
        Rectangle rect = (Rectangle) grid[row][col].getChildren().get(0);

        switch (type) {
            case "selected":
                rect.setFill(Color.GOLD);
                break;
            case "move-option":
                rect.setFill(Color.GOLD);
                break;
        }
    }


    


    public static void main(String[] args) 
    {
        launch(args);
    }

}
